import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Protocol, TypedDict, runtime_checkable

from google.protobuf import text_format
from langgraph.graph import END, StateGraph

# Import the compiled proto bindings
# workflow_pb2 is generated by:
#   python -m grpc_tools.protoc -I=schema/proto --python_out=schema/proto schema/proto/workflow.proto
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "schema" / "proto"))
import workflow_pb2  # noqa: E402

# ── OutputStatus lookup ──────────────────────────────────────────────────

_STATUS_ENUM = workflow_pb2.OutputStatus.DESCRIPTOR
_STATUS_NAME_BY_VALUE = {v.number: v.name for v in _STATUS_ENUM.values}
_UNSPECIFIED = workflow_pb2.OUTPUT_STATUS_UNSPECIFIED


# ── Dependency Injection Protocols ────────────────────────────────────────

@runtime_checkable
class WorkflowParser(Protocol):
    """Interface for parsing process definitions."""
    def parse(self, text: str) -> workflow_pb2.Process: ...
    def parse_file(self, path: Path) -> workflow_pb2.Process: ...


@runtime_checkable
class NodeFactory(Protocol):
    """Interface for creating executable node functions."""
    def create_node(self, node: workflow_pb2.Node) -> Any: ...


@runtime_checkable
class GraphBuilder(Protocol):
    """Interface for building and compiling the workflow graph."""
    def add_node(self, node_id: str, node_func: Any) -> None: ...
    def set_entry_point(self, node_id: str) -> None: ...
    def add_edge(self, start_node: str, end_node: str) -> None: ...
    def add_conditional_edges(self, source_id: str, router_func: Any, status_map: dict[str, str]) -> None: ...
    def compile(self) -> Any: ...


# ── Concrete Implementations (Defaults) ───────────────────────────────────

class ProtobufParser:
    """Default parser using native google.protobuf.text_format."""
    def parse(self, text: str) -> workflow_pb2.Process:
        process = workflow_pb2.Process()
        text_format.Parse(text, process)
        return process

    def parse_file(self, path: Path) -> workflow_pb2.Process:
        return self.parse(path.read_text(encoding="utf-8"))


class DefaultNodeFactory:
    """Creates stub node functions for visualization/testing."""
    def create_node(self, node: workflow_pb2.Node) -> Any:
        node_id = node.id
        node_name = node.name or node.id
        node_desc = node.description or "executing..."

        def _stub(state: dict) -> dict:
            print(f"  [{node_name}] {node_desc}")
            return {**state, "current_node": node_id}

        _stub.__name__ = node_id
        return _stub


class LangGraphBuilder:
    """Wraps LangGraph StateGraph implementation."""
    def __init__(self, state_schema: type):
        self._g = StateGraph(state_schema)

    def add_node(self, node_id: str, node_func: Any) -> None:
        if node_id != "end":
            self._g.add_node(node_id, node_func)

    def set_entry_point(self, node_id: str) -> None:
        self._g.set_entry_point(node_id)

    def add_edge(self, start_node: str, end_node: str) -> None:
        target = END if end_node == "end" else end_node
        self._g.add_edge(start_node, target)

    def add_conditional_edges(self, source_id: str, router_func: Any, status_map: dict[str, str]) -> None:
        self._g.add_conditional_edges(source_id, router_func, status_map)

    def compile(self) -> Any:
        return self._g.compile()


# ── Core Compiler (The Orchestrator) ─────────────────────────────────────

class ProcessState(TypedDict):
    """Minimal state carried through the compiled graph."""
    current_node: str
    output_status: str
    data: dict


class LangGraphCompiler:
    """
    Compiles a Process definition into a runnable graph.
    Uses Dependency Injection for all core behaviors.
    """
    def __init__(
        self,
        parser: WorkflowParser | None = None,
        node_factory: NodeFactory | None = None,
        builder_factory: Any | None = None
    ):
        self.parser = parser or ProtobufParser()
        self.node_factory = node_factory or DefaultNodeFactory()
        self.builder_factory = builder_factory or (lambda: LangGraphBuilder(ProcessState))

    def compile(self, textpb: str) -> Any:
        """Parse text and compile into a graph."""
        process = self.parser.parse(textpb)
        return self.compile_proto(process)

    def compile_proto(self, process: workflow_pb2.Process) -> Any:
        """Compile a native Process proto into a graph."""
        builder = self.builder_factory()

        # 1. Add nodes
        for node in process.nodes:
            if node.id == "end":
                continue
            builder.add_node(node.id, self.node_factory.create_node(node))

        # 2. Set entry point
        if process.entry_node_id:
            builder.set_entry_point(process.entry_node_id)

        # 3. Add edges (grouped by source)
        edges_by_source: dict[str, list[workflow_pb2.Edge]] = defaultdict(list)
        for edge in process.edges:
            edges_by_source[edge.from_node_id].append(edge)

        for source_id, edge_list in edges_by_source.items():
            if source_id == "end":
                continue

            unconditional = [e for e in edge_list if e.on_status == _UNSPECIFIED]
            conditional = [e for e in edge_list if e.on_status != _UNSPECIFIED]

            if unconditional and not conditional:
                for edge in unconditional:
                    builder.add_edge(source_id, edge.to_node_id)
            elif conditional:
                status_map: dict[str, str] = {}
                for edge in conditional:
                    status_name = _STATUS_NAME_BY_VALUE.get(edge.on_status, str(edge.on_status))
                    target = END if edge.to_node_id == "end" else edge.to_node_id
                    status_map[status_name] = target

                for edge in unconditional:
                    target = END if edge.to_node_id == "end" else edge.to_node_id
                    status_map["__default__"] = target

                builder.add_conditional_edges(source_id, self._make_router(status_map), status_map)

        return builder.compile()

    def _make_router(self, smap: dict[str, str]):
        """Create a router function for conditional edges."""
        def _router(state: ProcessState) -> str:
            status = state.get("output_status", "OUTPUT_STATUS_UNSPECIFIED")
            if status in smap:
                return smap[status]
            if "__default__" in smap:
                return smap["__default__"]
            return next(iter(smap.values()))
        return _router


# ── Utilities ────────────────────────────────────────────────────────────

def render_diagram(graph: Any, output_path: Path) -> Path:
    """Helper to render a compiled graph to PNG."""
    png_bytes = graph.get_graph().draw_mermaid_png()
    output_path.write_bytes(png_bytes)
    print(f"Diagram saved: {output_path}")
    return output_path


# ── CLI Entry Point ──────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: python engine/nodes/compiler.py <process.textpb> [--no-png]")
        sys.exit(1)

    textpb_path = Path(sys.argv[1])
    if not textpb_path.exists():
        print(f"Error: {textpb_path} not found")
        sys.exit(1)

    # Bootstrap with default implementations (Injection point)
    compiler = LangGraphCompiler()
    process = compiler.parser.parse_file(textpb_path)

    print(f"Process: {process.name}")
    graph = compiler.compile_proto(process)

    # Visual verify
    print("\n--- Graph (ASCII) ---")
    print(graph.get_graph().draw_ascii())

    if "--no-png" not in sys.argv:
        png_path = textpb_path.with_suffix(".png")
        render_diagram(graph, png_path)


if __name__ == "__main__":
    main()
