"""
Proto-Driven LangGraph Compiler
================================
Reads a Process definition in textpb format and compiles it into a
LangGraph StateGraph, then optionally renders a diagram PNG.

Uses native ``google.protobuf.text_format`` to parse textpb against
the compiled ``workflow_pb2`` bindings — no custom parser needed.

Usage:
    python -m engine.nodes.compiler <path/to/process.textpb> [--no-png]

The textpb must define a ``Process`` message per workflow.proto.
"""

import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, TypedDict

from google.protobuf import text_format
from langgraph.graph import END, StateGraph

# Import the compiled proto bindings
# workflow_pb2 is generated by:
#   python -m grpc_tools.protoc -I=schema/proto --python_out=schema/proto schema/proto/workflow.proto
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "schema" / "proto"))
import workflow_pb2  # noqa: E402

# ── OutputStatus enum name lookup ─────────────────────────────────────────

_STATUS_ENUM = workflow_pb2.OutputStatus.DESCRIPTOR
_STATUS_NAME_BY_VALUE = {v.number: v.name for v in _STATUS_ENUM.values}
_UNSPECIFIED = workflow_pb2.OUTPUT_STATUS_UNSPECIFIED


# ── Parse textpb → proto message ─────────────────────────────────────────

def parse_textpb(text: str) -> workflow_pb2.Process:
    """Parse a textpb string into a native protobuf Process message."""
    process = workflow_pb2.Process()
    text_format.Parse(text, process)
    return process


def parse_textpb_file(path: Path) -> workflow_pb2.Process:
    """Parse a textpb file into a native protobuf Process message."""
    return parse_textpb(path.read_text(encoding="utf-8"))


# ── LangGraph compiler ───────────────────────────────────────────────────

class ProcessState(TypedDict):
    """Minimal state carried through the compiled graph."""
    current_node: str
    output_status: str
    data: dict


def _make_stub_node(node: workflow_pb2.Node):
    """Create a stub node function for a given proto Node."""
    node_id = node.id
    node_name = node.name or node.id
    node_desc = node.description or "executing..."

    def _stub(state: ProcessState) -> ProcessState:
        print(f"  [{node_name}] {node_desc}")
        return {**state, "current_node": node_id}

    _stub.__name__ = node_id
    _stub.__qualname__ = node_id
    return _stub


def compile_process(process: workflow_pb2.Process) -> Any:
    """
    Compile a Process proto into a LangGraph StateGraph.

    Returns the compiled graph (ready for .invoke() or .get_graph()).
    """
    g = StateGraph(ProcessState)

    # Add nodes (skip explicit "end" — LangGraph has built-in END)
    for node in process.nodes:
        if node.id == "end":
            continue
        g.add_node(node.id, _make_stub_node(node))

    # Set entry point
    if process.entry_node_id:
        g.set_entry_point(process.entry_node_id)

    # Group edges by from_node_id
    edges_by_source: dict[str, list[workflow_pb2.Edge]] = defaultdict(list)
    for edge in process.edges:
        edges_by_source[edge.from_node_id].append(edge)

    for source_id, edge_list in edges_by_source.items():
        if source_id == "end":
            continue

        unconditional = [e for e in edge_list if e.on_status == _UNSPECIFIED]
        conditional = [e for e in edge_list if e.on_status != _UNSPECIFIED]

        if unconditional and not conditional:
            # Simple linear edges
            for edge in unconditional:
                target = END if edge.to_node_id == "end" else edge.to_node_id
                g.add_edge(source_id, target)
        elif conditional:
            # Build conditional edge map: status_name -> target_node
            status_map: dict[str, str] = {}
            for edge in conditional:
                status_name = _STATUS_NAME_BY_VALUE.get(edge.on_status, str(edge.on_status))
                target = END if edge.to_node_id == "end" else edge.to_node_id
                status_map[status_name] = target

            # Unconditional edges become default fallback
            for edge in unconditional:
                target = END if edge.to_node_id == "end" else edge.to_node_id
                status_map["__default__"] = target

            # Create router function
            def _make_router(smap: dict[str, str]):
                def _router(state: ProcessState) -> str:
                    status = state.get("output_status", "OUTPUT_STATUS_UNSPECIFIED")
                    if status in smap:
                        return smap[status]
                    if "__default__" in smap:
                        return smap["__default__"]
                    return next(iter(smap.values()))
                return _router

            g.add_conditional_edges(source_id, _make_router(status_map), status_map)

    return g.compile()


# ── Diagram rendering ─────────────────────────────────────────────────────

def render_diagram(process: workflow_pb2.Process, output_path: Path | None = None) -> Path:
    """
    Compile the process and render its graph as a PNG diagram.

    Returns the path to the generated PNG file.
    """
    graph = compile_process(process)

    if output_path is None:
        output_path = Path("graph.png")

    png_bytes = graph.get_graph().draw_mermaid_png()
    output_path.write_bytes(png_bytes)
    print(f"Diagram saved: {output_path}")
    return output_path


# ── CLI entry point ───────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: python -m engine.nodes.compiler <process.textpb> [--no-png]")
        print("       python engine/nodes/compiler.py <process.textpb> [--no-png]")
        sys.exit(1)

    textpb_path = Path(sys.argv[1])
    if not textpb_path.exists():
        print(f"Error: {textpb_path} not found")
        sys.exit(1)

    process = parse_textpb_file(textpb_path)

    print(f"Process: {process.name}")
    print(f"  Nodes: {[n.id for n in process.nodes]}")
    print(f"  Edges: {[(e.from_node_id, e.to_node_id, _STATUS_NAME_BY_VALUE.get(e.on_status)) for e in process.edges]}")
    print(f"  Rules: {[(r.node_id, r.max_runs, _STATUS_NAME_BY_VALUE.get(r.override_status)) for r in process.rules]}")

    graph = compile_process(process)

    # Print ASCII + Mermaid
    print("\n--- Graph (ASCII) ---")
    print(graph.get_graph().draw_ascii())
    print("\n--- Mermaid source ---")
    print(graph.get_graph().draw_mermaid())

    # Render PNG unless explicitly disabled
    if "--no-png" not in sys.argv:
        png_path = textpb_path.parent / textpb_path.stem
        png_path = png_path.with_suffix(".png")
        render_diagram(process, png_path)


if __name__ == "__main__":
    main()
